export enum Section {
    Business = "business",
    BusinessProperty = "business/property",
    BusinessIndustries = "business/industries",
    BusinessMoney = "business/money",
    BusinessFarming = "business/farming",
    BusinessOpinionAnalysis = "business/opinion-analysis",
    BusinessSmallBusiness = "business/small-business",
    BusinessWorld = "business/world",

    Entertainment = "entertainment",
    EntertainmentCelebrities = "entertainment/celebrities",
    EntertainmentFilm = "entertainment/film",
    EntertainmentMusic = "entertainment/music",
    EntertainmentTVRadio = "entertainment/tv-radio",
    EntertainmentGames = "entertainment/games",
    EntertainmentBooks = "entertainment/books",
    EntertainmentArts = "entertainment/arts",

    Environment = "environment",

    LifeStyle = "life-style",
    LifeStyleChristmas = "life-style/christmas",
    LifeStyleLoveSex = "life-style/love-sex",
    LifeStyleWellGood = "life-style/well-good",
    LifeStyleFoodWine = "life-style/food-wine",
    LifeStyleParenting = "life-style/parenting",
    LifeStyleBeauty = "life-style/beauty",
    LifeStyleFashion = "life-style/fashion",
    LifeStyleHomed = "life-style/homed",
    LifeStyleWeddings = "life-style/weddings",
    LifeStyleCuteStuff = "life-style/cutestuff",
    LifeStylePuzzles = "life-style/puzzles",

    Motoring = "motoring",
    MotoringNews = "motoring/news",
    MotoringLifestyleVehicles = "motoring/lifestyle-vehicles",
    MotoringRoadTests = "motoring/road-tests",
    MotoringCustomsClassics = "motoring/customs-classics",
    MotoringBikes = "motoring/bikes",
    MotoringTopCars = "motoring/top-cars",
    MotoringTrendsSUVsVans = "motoring/trends-in-suvs-and-vans",

    National = "national",
    NationalCrime = "national/crime",
    NationalEarthquakes = "national/nz-earthquake",
    NationalPolitics = "national/politics",
    NationalStuffCircuit = "national/stuff-circuit",
    NationalEducation = "national/education",
    NationalHealth = "national/health",
    National1NewsNow = "national/1-news-now",
    NationalMaoriTV = "national/maori-television",
    NationalWeather = "national/weather",
    NationalQuizzes = "national/quizzes",

    Opinion = "opinion",
    OpinionCartoons = "opinion/cartoons",

    Science = "science",

    Sport = "sport",
    SportScores = "sport/scores",
    SportOpinion = "sport/opinion",
    SportRugby = "sport/rugby",
    SportCricket = "sport/cricket",
    SportLeague = "sport/league",
    SportFootball = "sport/football",
    SportBasketball = "sport/basketball",
    SportNetball = "sport/netball",
    SportTennis = "sport/tennis",
    SportOther = "sport/other-sports",
    SportMotorsport = "sport/motorsport",
    SportRacing = "sport/racing",
    SportCombat = "sport/combat-sports",

    Travel = "travel",
    TravelDestinations = "travel/destinations",
    TravelThemes = "travel/themes",
    TravelNews = "travel/news",
    TravelTroubles = "travel/travel-troubles",
    TravelCruising = "travel/cruising",
    TravelSnow = "travel/snow",
    TravelKiwiTraveller = "travel/kiwi-traveller",

    World = "world",
    WorldAustralia = "world/australia",
    WorldAmericas = "world/americas",
    WorldNorthAmerica = "world/americas/donald-trumps-america",
    WorldEurope = "world/europe",
    WorldMiddleEast = "world/middle-east",
    WorldAsia = "world/asia",
    WorldAfrica = "world/africa",
    WorldSouthPacific = "world/south-pacific",

}
